# Generated by Django 3.2 on 2022-07-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220630_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='owner',
            new_name='user',
        ),
    ]
